name: js test

# to run tasks that would need to run before releasing

on:
  push:
    branches:
      - master # run on pushed commits to `master`
  pull_request:
    branches:
      - master # run on pull requests to `master`

jobs:
  prerelease:
    runs-on: ubuntu-latest

    name: Run prerelease scripts

    strategy:
      matrix:
        node-version:
          - 14.x

    steps:
      - name: Checkout js repo
        uses: actions/checkout@v2
        with:
          repository: indic-transliteration/sanscript.js
          submodules: true
          path: js
          fetch-depth: 1
      - uses: actions/checkout@v2
        with:
          path: js/src/schemes
          fetch-depth: 1
      - name: Set content to pull request
        if: ${{ github.event_name == 'pull_request'}}
        uses: actions/checkout@master
        with:
          path: js/src/schemes
      - name : Use Node.js version ${{ matrix.node-version }}
        uses : actions/setup-node@v2
        with :
          node-version: ${{ matrix.node-version }}

      - name : Load node-modules cache
        uses : actions/cache@v2
        env  :
          cache-name: cache-node-modules
        with :
          path: ~/.npm
          key: ${{ runner.os }}-${{ matrix.node-version }}-prerelease-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-prerelease-${{ env.cache-name }}-
            ${{ runner.os }}-${{ matrix.node-version }}-prerelease-
            ${{ runner.os }}-

      - name : Install dependencies
        run: |
          cd js
          npm install
          cd ..
      # The below steps are basically `npm run prepare`
      # split out to improve visibility in case we need
      # to debug.

      - name : Run validation
        run: |
          cd js
          npm run validate
          cd ..
      - name : Build dist build
        run: |
          cd js
          npm run build
          cd ..
      - name : Run transpilation
        run: |
          cd js
          npm run tranpile
          cd ..
      - name : Run tests
        run: |
          cd js
          npm run test
          cd ..
